apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-config
  namespace: {{ .Values.namespace }}
data:
  postgres-db: "{{ .Values.postgres.env.db }}"
  postgres-user: "{{ .Values.postgres.env.user }}"
  postgres-host: "{{ .Values.appName }}-postgres"
  postgres-port: "{{ .Values.postgres.service.port }}"

  app-host: "0.0.0.0"

  backend-hostname: "{{ .Values.appName }}-backend"
  backend-port: "{{ .Values.backend.service.port }}"